services:
  wireguard:
    build: .
    network_mode: "host"
    environment:
      SERVER_PORT: 51820
    ports:
      - "51820:51820/udp"
    volumes:
      - ./config:/etc/wireguard
    secrets:
      - client_pub_key
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    privileged: true

secrets:
  client_pub_key:
    file: ./client-public-key.txt

