version: '3.8'
services:
  wireguard:
    build: .
    environment:
      - SERVER_PORT=${SERVER_PORT:-51820}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
    volumes:
      - ./config:/etc/wireguard
    secrets:
      - client_public_key
    restart: unless-stopped

secrets:
  client_public_key:
    file: ./client-public-key.txt

