services:
  wireguard:
    container_name: wireguardVPN
    build: .
    network_mode: "host"
    env_file:
      - path: ./env
    #ports:
    # - "51820:51820/udp"
    volumes:
      - ./config:/etc/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    #sysctls:
    # - net.ipv4.ip_forward=1
    # - net.ipv6.conf.all.forwarding=1
    privileged: true
