version: '3.8'
services:
  wireguard:
    build: .
    ports:
      - 51820:51820/udp
    volumes:
      - ./config:/etc/wireguard
    secrets:
      - client_public_key
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    privileged: true
    secrets:
      - client_public_key

secrets:
  client_public_key:
    file: ./client-public-key.txt

