version: '3.8'
services:
  wireguard:
    build: .
    environment:
    ports:
      - 51820:51820/udp
    volumes:
      - ./config:/etc/wireguard
    secrets:
      - client_public_key
    restart: unless-stopped

secrets:
  client_public_key:
    file: ./client-public-key.txt

